#!/bin/python3

import math
import os
import random
import re
import sys



#
# Complete the 'strmethod' function below.
#
# The function accepts following parameters:
#  1. STRING para
#  2. STRING spch1
#  3. STRING spch2
#  4. LIST li1
#  5. STRING strf
#

def stringmethod(para, special1, special2, list1, strfind):
    # Write your code here
    word1=re.sub(f"[{special1}]", "", para)
    rword2=word1[:70][::-1]
    print(rword2)
    temp=rword2.replace(" ", "").strip()
    temp=special2.join(temp)
    print(temp)
    
    if all ( list1_item in para for list1_item in list1):
        print(f"Every string in {list1} were present")
    else:
        print(f"Every string in {list1} were not present")

    s=word1.split()
    print(s[:20])
    
    unique_list=[]
    final_list=[]

    for i in s:
      if i not in unique_list:
        unique_list.append(i)
    for i in unique_list:
      if s.count(i) < 3:
        final_list.append(i)
    print(final_list[-20:])
    
    print(word1.rindex(strfind))

if __name__ == '__main__':
    para = input()

    spch1 = input()

    spch2 = input()
    
    qw1_count = int(input().strip())

    qw1 = []

    for _ in range(qw1_count):
        qw1_item = input()
        qw1.append(qw1_item)

    strf = input()

    stringmethod(para, spch1, spch2, qw1, strf)
